version: '3.5'

services:

  umi-serve:
    build: ./umi-serve
    ports:
      - 8001:8001
    container_name: umi-serve
    restart: unless-stopped
    command: umi-serve

  crystalca:
    image: nginx:alpine
    ports:
      - 80:80
    container_name: crystalca
    depends_on:
      - umi-serve
    restart: unless-stopped
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:
